// Human-Designer Curated Color Palettes for Chalk Frames
// Inspired by industrial design, Swiss typography, architecture, and editorial print.

export const DESIGNER_PALETTES = {
  "braun-industrial": {
    id: "braun-industrial",
    name: "Braun Industrial",
    description:
      "Functionalist German industrial design. Warm matte putty paper with signal amber dial accent.",
    background: "#f4f1ea",
    card: "#ffffff",
    border: "#e2ddd3",
    text: "#1c1b18",
    textMuted: "#7c776e",
    muted: "#7c776e",
    accent: "#e65100",
    accentDark: "#b33c00",
    accentText: "#ffffff",
    isDark: false,
  },
  "tokyo-metro": {
    id: "tokyo-metro",
    name: "Tokyo Metro",
    description:
      "Minimalist Japanese transit signage and Sony dark mode. Deep obsidian with high-legibility phosphor mint.",
    background: "#090b0e",
    card: "#13171d",
    border: "#212732",
    text: "#e6edf3",
    textMuted: "#7d8590",
    muted: "#7d8590",
    accent: "#00dc82",
    accentDark: "#00b86c",
    accentText: "#090b0e",
    isDark: true,
  },
  "broadside-editorial": {
    id: "broadside-editorial",
    name: "Broadside Editorial",
    description:
      "Traditional broadsheet newsprint and letterpress typography with burnt sienna red.",
    background: "#fdf0e2",
    card: "#fff7ee",
    border: "#eddcd0",
    text: "#1e1915",
    textMuted: "#6e645e",
    muted: "#6e645e",
    accent: "#b83a24",
    accentDark: "#8e2a18",
    accentText: "#ffffff",
    isDark: false,
  },
  "swiss-international": {
    id: "swiss-international",
    name: "Swiss International",
    description:
      "Josef Müller-Brockmann high-contrast grid system. Sterile gallery canvas with signal vermilion.",
    background: "#f8f9fa",
    card: "#ffffff",
    border: "#e5e7eb",
    text: "#0f1115",
    textMuted: "#6b7280",
    muted: "#6b7280",
    accent: "#e11d48",
    accentDark: "#be123c",
    accentText: "#ffffff",
    isDark: false,
  },
  "nordic-fjord": {
    id: "nordic-fjord",
    name: "Nordic Fjord",
    description:
      "Scandinavian architectural minimalism. Deep sub-arctic navy and granite with glacial cyan.",
    background: "#0b0f17",
    card: "#141a24",
    border: "#222b3a",
    text: "#f1f5f9",
    textMuted: "#94a3b8",
    muted: "#94a3b8",
    accent: "#38bdf8",
    accentDark: "#0ea5e9",
    accentText: "#0b0f17",
    isDark: true,
  },
  "risograph-studio": {
    id: "risograph-studio",
    name: "Risograph Studio",
    description: "Unbleached cotton stock printed with vibrant fluoro-persimmon soy ink.",
    background: "#f4eedb",
    card: "#ebe3ce",
    border: "#d8ceb5",
    text: "#2c2825",
    textMuted: "#7a7065",
    muted: "#7a7065",
    accent: "#ff5733",
    accentDark: "#d9381e",
    accentText: "#ffffff",
    isDark: false,
  },
  "solarized-amber": {
    id: "solarized-amber",
    name: "Solarized Amber",
    description: "Retro phosphor terminal engineering. Deep basalt black with warm cathode amber.",
    background: "#071013",
    card: "#0f1e24",
    border: "#1d333c",
    text: "#eae6df",
    textMuted: "#839496",
    muted: "#839496",
    accent: "#d97706",
    accentDark: "#b45309",
    accentText: "#071013",
    isDark: true,
  },
  "kyoto-matcha": {
    id: "kyoto-matcha",
    name: "Kyoto Matcha",
    description:
      "Cedar and slate Japanese tea house. Deep soot charcoal with organic matcha green.",
    background: "#0d1310",
    card: "#151e19",
    border: "#233229",
    text: "#ecf3ef",
    textMuted: "#81978b",
    muted: "#81978b",
    accent: "#4ade80",
    accentDark: "#22c55e",
    accentText: "#0d1310",
    isDark: true,
  },
  "bauhaus-dessau": {
    id: "bauhaus-dessau",
    name: "Bauhaus Dessau",
    description:
      "Dessau archival materials. Chalk plaster, clean geometric cards, and Yves Klein ultramarine blue.",
    background: "#f6f4f0",
    card: "#ffffff",
    border: "#ded9d0",
    text: "#18181b",
    textMuted: "#71717a",
    muted: "#71717a",
    accent: "#1d4ed8",
    accentDark: "#1e40af",
    accentText: "#ffffff",
    isDark: false,
  },
  "monolith-titanium": {
    id: "monolith-titanium",
    name: "Monolith Titanium",
    description:
      "Brutalist matte aluminum and technical documentation. Monochromatic black with brushed titanium silver.",
    background: "#111111",
    card: "#1a1a1a",
    border: "#2d2d2d",
    text: "#f5f5f5",
    textMuted: "#888888",
    muted: "#888888",
    accent: "#d4d4d8",
    accentDark: "#a1a1aa",
    accentText: "#111111",
    isDark: true,
  },
};

// Backwards-compatible palette mapping
export const LEGACY_PALETTES = {
  "warm-ivory": {
    id: "warm-ivory",
    name: "Warm Ivory",
    description: "Warm editorial paper with vermilion accent",
    background: "#f7f6f2",
    text: "#141412",
    accent: "#e25329",
    muted: "#57554f",
    textMuted: "#45433e",
    accentDark: "#bd4522",
    accentText: "#ffffff",
    card: "#ffffff",
    border: "#e5e2da",
    isDark: false,
  },
  "midnight-velvet": {
    id: "midnight-velvet",
    name: "Midnight Velvet",
    description: "Deep obsidian with purple violet accent",
    background: "#09090d",
    text: "#f4f4f7",
    accent: "#8b5cf6",
    muted: "#888899",
    textMuted: "#9898ab",
    accentDark: "#a78bfa",
    accentText: "#ffffff",
    card: "#13131c",
    border: "#20202e",
    isDark: true,
  },
  "cyber-slate": {
    id: "cyber-slate",
    name: "Cyber Slate",
    description: "Dark slate with cyan accent",
    background: "#0a0e17",
    text: "#e2e8f0",
    accent: "#06b6d4",
    muted: "#748296",
    textMuted: "#8899aa",
    accentDark: "#22d3ee",
    accentText: "#09090d",
    card: "#111827",
    border: "#1e293b",
    isDark: true,
  },
  "emerald-noir": {
    id: "emerald-noir",
    name: "Emerald Noir",
    description: "Deep green obsidian with mint accent",
    background: "#070b09",
    text: "#f0fdf4",
    accent: "#10b981",
    muted: "#6b8076",
    textMuted: "#7d9e92",
    accentDark: "#34d399",
    accentText: "#070b09",
    card: "#0e1813",
    border: "#182b22",
    isDark: true,
  },
};

export const PALETTES = {
  ...DESIGNER_PALETTES,
  ...LEGACY_PALETTES,
};

export const PALETTE_LIST = Object.values(DESIGNER_PALETTES);
