// 10 CC0 Public Domain Background Soundtracks
// Released under Creative Commons Zero (CC0 1.0 Universal - Public Domain Dedication)
// Zero copyright restrictions, safe for commercial, open-source, and offline distribution.

export const SOUNDTRACKS = [
  {
    id: "quiet-reflection",
    file: "quiet-reflection.mp3",
    title: "This Pain is Soft But Here",
    name: "Quiet Reflection",
    artist: "Loyalty Freak Music",
    license: "CC0 1.0 Universal (Public Domain)",
    genre: "Soft Rhodes electric piano and warm lo-fi ambience",
    desc: "Soft Rhodes electric piano and warm lo-fi ambience",
    bestFor: "Product walk-throughs, UI demos, and thoughtful engineering explainers",
  },
  {
    id: "ambient-drift",
    file: "ambient-drift.mp3",
    title: "Chill Awash",
    name: "Ambient Drift",
    artist: "Kevin MacLeod (FreePD)",
    license: "CC0 1.0 Universal (Public Domain)",
    genre: "Slow analog synth pad with a warm sub-bass pulse",
    desc: "Slow analog synth pad with a warm sub-bass pulse",
    bestFor: "Complex systems architecture, distributed networks, and cloud pipelines",
  },
  {
    id: "minimal-clarity",
    file: "minimal-clarity.mp3",
    title: "Gymnopédie No. 1",
    name: "Minimal Clarity",
    artist: "Erik Satie (perf. Robin Alciatore, Musopen)",
    license: "Public Domain Mark / CC0",
    genre: "Minimalist solo classical piano",
    desc: "Minimalist solo classical piano",
    bestFor: "Deep mathematical proofs, calculus, and foundational algorithms",
  },
  {
    id: "gentle-pulse",
    file: "gentle-pulse.mp3",
    title: "It Feels Good To Be Alive Too",
    name: "Gentle Pulse",
    artist: "Loyalty Freak Music",
    license: "CC0 1.0 Universal (Public Domain)",
    genre: "Warm acoustic guitar pluck and subtle downtempo electronic hum",
    desc: "Warm acoustic guitar pluck and subtle downtempo electronic hum",
    bestFor: "Company pitches, vision explainers, and macroeconomic overviews",
  },
  {
    id: "deliberate-thought",
    file: "deliberate-thought.mp3",
    title: "Ambient L Delicate",
    name: "Deliberate Thought",
    artist: "Kevin MacLeod (FreePD)",
    license: "CC0 1.0 Universal (Public Domain)",
    genre: "Cinematic soft drone with muted strings and peaceful resonance",
    desc: "Cinematic soft drone with muted strings and peaceful resonance",
    bestFor: "Research paper breakdowns and technical deep dives",
  },
  {
    id: "gnossienne-clarity",
    file: "gnossienne-clarity.mp3",
    title: "Gnossienne No. 1",
    name: "Gnossienne Clarity",
    artist: "Erik Satie (perf. La Pianista)",
    license: "Public Domain Mark / CC0",
    genre: "Meditative solo classical piano, calm and reflective, zero beats",
    desc: "Mystical, serene French impressionist piano with gentle pacing and no percussion",
    bestFor: "Deep conceptual explainers, foundational ideas, and thoughtful tutorials",
  },
  {
    id: "clair-de-lune",
    file: "clair-de-lune.mp3",
    title: "Clair de Lune (Suite bergamasque)",
    name: "Clair de Lune",
    artist: "Claude Debussy (perf. Laurens Goedhart)",
    license: "Public Domain Mark / CC0",
    genre: "Lyrical, peaceful classical impressionist piano, zero beats",
    desc: "Famous tranquil piano nocturne with floating, soothing melodies and zero drums",
    bestFor: "Product stories, visionary keynote recaps, and inspiring demonstrations",
  },
  {
    id: "chopin-nocturne-20",
    file: "chopin-nocturne-20.mp3",
    title: "Nocturne No. 20 in C-sharp minor, B. 49",
    name: "Nocturne Serenata",
    artist: "Frédéric Chopin (perf. Frank Lévy, Musopen)",
    license: "CC0 1.0 Universal / Public Domain",
    genre: "Delicate, emotive solo piano, quiet and expressive, zero beats",
    desc: "Gentle, deeply moving romantic piano melody with warm harmonic resonance",
    bestFor: "Narrative case studies, user stories, and high-impact technical journeys",
  },
  {
    id: "chopin-nocturne-19",
    file: "chopin-nocturne-19.mp3",
    title: "Nocturne No. 19 in E minor, Op. 72 No. 1",
    name: "Midnight Solitude",
    artist: "Frédéric Chopin (perf. Luke Faulkner, Musopen)",
    license: "CC0 1.0 Universal / Public Domain",
    genre: "Introspective atmospheric classical piano, zero beats",
    desc: "Warm, resonant, contemplative piano with rich acoustic tone and zero drums",
    bestFor: "Software architecture walkthroughs, system diagrams, and deep dives",
  },
  {
    id: "chopin-nocturne-21",
    file: "chopin-nocturne-21.mp3",
    title: "Nocturne No. 21 in C minor, B. 108",
    name: "Pastoral Reflection",
    artist: "Frédéric Chopin (perf. Diana Hughes, Musopen)",
    license: "CC0 1.0 Universal / Public Domain",
    genre: "Peaceful, tender classical piano, zero beats",
    desc: "Quiet, tender solo piano with soothing warmth and serene pacing",
    bestFor: "Educational videos, mathematical overviews, and clean product guides",
  },
];

export const SOUNDTRACK_MAP = {
  // 10 Flagship CC0 Soundtracks
  ...Object.fromEntries(SOUNDTRACKS.map((t) => [t.id, t])),

  // Backward-compatible legacy aliases
  "soothing-ambient": {
    file: "soothing-ambient.mp3",
    name: "Soothing Ambient",
    desc: "Gentle and warm ambient pulse, relaxing and unobtrusive",
  },
  "modern-tech": {
    file: "modern-tech.mp3",
    name: "Modern Tech",
    desc: "Kinetic SaaS groove with subtle upbeat percussion",
  },
  "chill-lofi": {
    file: "chill-lofi.mp3",
    name: "Chill Horizon",
    desc: "Relaxing electronic lo-fi with atmospheric chords",
  },
  "acoustic-warmth": {
    file: "acoustic-warmth.mp3",
    name: "Acoustic Warmth",
    desc: "Warm acoustic piano and strings, emotional and human",
  },
};
