from . import (
    activation_functions,
    backprop_chain,
    basis_change,
    bayes_theorem,
    convolution_kernel,
    dot_cross_product,
    eigen_decomposition,
    function_plot,
    gradient_descent_3d,
    hyperplane_separator,
    kv_cache,
    latent_manifold,
    markov_chain,
    monte_carlo_pi,
    network_topology,
    positional_rope,
    residual_stream,
    sorting_visualizer,
    svd_transform,
    temperature_softmax,
    token_unembedding,
    transformer_block,
    vector_transform,
)

PRIMITIVES = {
    "manim-function-plot": function_plot,
    "manim-vector-transform": vector_transform,
    "manim-network-topology": network_topology,
    "manim-transformer-block": transformer_block,
    "manim-kv-cache": kv_cache,
    "manim-positional-rope": positional_rope,
    "manim-token-unembedding": token_unembedding,
    "manim-residual-stream": residual_stream,
    "manim-temperature-softmax": temperature_softmax,
    "manim-gradient-descent-3d": gradient_descent_3d,
    "manim-backprop-chain": backprop_chain,
    "manim-convolution-kernel": convolution_kernel,
    "manim-svd-transform": svd_transform,
    "manim-latent-manifold": latent_manifold,
    "manim-eigen-decomposition": eigen_decomposition,
    "manim-activation-functions": activation_functions,
    "manim-dot-cross-product": dot_cross_product,
    "manim-hyperplane-separator": hyperplane_separator,
    "manim-basis-change": basis_change,
    "manim-sorting-visualizer": sorting_visualizer,
    "manim-monte-carlo-pi": monte_carlo_pi,
    "manim-markov-chain": markov_chain,
    "manim-bayes-theorem": bayes_theorem,
}

